const $ = id => document.getElementById(id);
let state, videoState, loading = false, generating = false, reviewId = null, reviewVersion = null, reviewDirty = false;
let personaSignature = '', jobsSignature = '', reviewSignature = '', pendingRequest = null;
let uploadedReference = null, uploading = false, draftRestored = false;
const draftFields = ['video-persona','video-source','video-title','video-storyboard','video-caption','video-voice-script','video-duration','video-resolution'];
function saveDraft(){try{sessionStorage.setItem('boca-video-draft',JSON.stringify({fields:Object.fromEntries(draftFields.map(id=>[id,$(id).value])),textOnly:$('video-text-only').checked,reference:uploadedReference}));}catch{}}
function restoreDraft(){if(draftRestored)return;draftRestored=true;try{const draft=JSON.parse(sessionStorage.getItem('boca-video-draft')||'null');if(!draft)return;for(const id of draftFields){const el=$(id),value=draft.fields?.[id];if(typeof value!=='string')continue;if(el.tagName==='SELECT'&&![...el.options].some(o=>o.value===value))continue;el.value=value;if(id==='video-persona')renderSources();}$('video-text-only').checked=draft.textOnly===true;if(/^[a-f0-9]{64}\.(png|jpg|webp)$/.test(draft.reference?.media||''))uploadedReference={media:draft.reference.media,url:'/media/'+draft.reference.media};}catch{}}
const labels = {queued:'생성 대기',preparing:'참조 이미지 준비 중',submitting:'생성 요청 중',running:'영상 생성 중',downloading:'영상 저장 중',completed:'검토 대기',failed:'생성 실패',uncertain:'요청 결과 확인 필요',attention:'결과 조회 확인 필요'};
function node(tag, text, cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').hidden=true,8000);}
async function get(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error('서버 연결을 확인해 주세요.');return r.json();}
async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-BOCA-Token':state.token},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){const error=Error(data.error||'요청에 실패했습니다.');error.status=r.status;throw error;}return data;}
const persona = () => state?.studio?.personas.find(p=>p.id===$('video-persona').value);
const source = () => state?.contents.find(c=>c.id===$('video-source').value);
function renderSources(){const old=$('video-source').value;$('video-source').replaceChildren(new Option('페르소나 기준 이미지 사용',''));for(const c of state.contents.filter(c=>c.persona_id===persona()?.id&&c.payload.cards.some(c=>!c.media.endsWith('.mp4'))))$('video-source').append(new Option(c.payload.title+' · v'+c.current_version,c.id));if([...$('video-source').options].some(o=>o.value===old))$('video-source').value=old;renderReference();}
function renderReference(){
  const p=persona(),s=source(),fixed=Boolean(p?.portrait_url),toggle=$('video-text-only');
  if(fixed)toggle.checked=false;
  toggle.disabled=fixed;
  const textOnly=toggle.checked;
  $('reference-note').textContent=fixed?'이 페르소나의 등록 사진을 모든 장면의 인물 기준으로 사용합니다. 추가 이미지는 장소·소품 참고용입니다.':textOnly?'기준 이미지 없이 생성하는 시안입니다. 기존 페르소나와 외형이 달라질 수 있습니다.':uploadedReference?'업로드한 이미지를 이 영상의 외형 기준으로 사용합니다.':s?'선택한 콘텐츠의 이미지를 외형·장면 참조로 사용합니다.':'기준 이미지가 없습니다. 아래에서 이미지를 업로드하거나 텍스트 시안을 선택해 주세요.';
  $('reference-upload-label').textContent=fixed?'추가 장면 참고 이미지 (선택)':'이 영상의 기준 이미지';
  $('reference-upload-help').textContent=fixed?'PNG·JPEG·WebP, 10MB 이하. 장소·소품을 참고하며 등록된 인물 사진은 그대로 사용합니다.':'PNG·JPEG·WebP, 10MB 이하. 선택한 이미지는 이 영상에만 사용하며 페르소나 원본을 변경하지 않습니다.';
  $('text-only-help').textContent=fixed?'등록된 인물 사진이 있어 기준 이미지 생략 옵션을 사용할 수 없습니다.':'텍스트 시안은 기존 페르소나와 같은 얼굴을 유지하지 못할 수 있습니다.';
  const blocker=!videoState?.connection.verified?'Segmind API 연결 확인이 필요합니다.':uploading?'기준 이미지를 저장하고 있습니다.':!p?'페르소나를 선택해 주세요.':!(textOnly||uploadedReference||p.portrait_url||s)?'기준 이미지 업로드 또는 ‘기준 이미지 없이 시안 생성’ 선택이 필요합니다.':'';
  $('generate-blocker').textContent=blocker;$('generate-blocker').hidden=!blocker;
  $('generate-button').disabled=generating||Boolean(blocker);
  const preview=fixed?p.portrait_url:uploadedReference?.url;
  $('reference-preview').hidden=!preview||textOnly;
  $('reference-preview').alt=fixed?p.display_name+'의 고정 인물 기준 사진':'업로드한 영상 기준 이미지';
  if(preview&&$('reference-preview').getAttribute('src')!==preview)$('reference-preview').src=preview;
}
function renderEstimate(){const duration=Number($('video-duration').value);const cost=duration*($('video-resolution').value==='480p'?.1065:.2389);$('cost-estimate').textContent='예상 사용량 $'+cost.toFixed(2);$('generate-button').textContent=generating?'요청 저장 중…':'영상 생성 · 약 $'+cost.toFixed(2);if(videoState)$('budget-note').textContent='현재 한도: 하루 예상 $'+videoState.config.daily_estimated_budget_usd+' · 대기/진행 '+videoState.config.max_pending+'건 (날짜 기준 UTC)';}
async function refresh(){if(loading)return;loading=true;try{[state,videoState]=await Promise.all([get('/api/state'),get('/api/video')]);const connection=videoState.connection;$('video-connection').textContent=connection.verified?'Segmind 인증 확인됨':connection.configured?'API 키 검증 필요':'API 키 연결 필요';if(connection.verified)$('key-panel').open=false;const signature=JSON.stringify(state.studio.personas.map(p=>[p.id,p.version,p.display_name,p.portrait_url]));if(signature!==personaSignature){const selected=$('video-persona').value||state.studio.active_persona_id;personaSignature=signature;$('video-persona').replaceChildren(...state.studio.personas.map(p=>new Option(p.display_name+' · v'+p.version,p.id)));if([...$('video-persona').options].some(o=>o.value===selected))$('video-persona').value=selected;renderSources();}else renderSources();restoreDraft();renderReference();renderEstimate();renderGuides();renderJobs();renderReview();}finally{loading=false;}}
$('key-form').onsubmit=async e=>{e.preventDefault();if(!state)return;$('connect-button').disabled=true;try{const body=$('api-key').value?{api_key:$('api-key').value}:{};await post('/api/video/connect',body);$('api-key').value='';await refresh();notify('Segmind API 인증을 확인했습니다. 영상 생성 시 크레딧을 사용합니다.');}catch(error){notify(error.message);}finally{$('connect-button').disabled=false;}};
$('video-persona').onchange=()=>{pendingRequest=null;uploadedReference=null;$('video-reference').value='';renderSources();saveDraft();};
$('video-source').onchange=()=>{pendingRequest=null;const c=source();if(c){$('video-title').value=c.payload.title;$('video-caption').value=c.payload.caption;const sb=c.payload.storyboard;$('video-storyboard').value=typeof sb==='string'?sb:c.payload.cards.map((card,i)=>'장면 '+(i+1)+': '+card.alt).join('\n');}renderReference();saveDraft();};
$('video-form').addEventListener('input',()=>{pendingRequest=null;renderReference();renderEstimate();saveDraft();});
$('video-reference').onchange=async()=>{
  const file=$('video-reference').files[0];if(!file)return;
  uploading=true;pendingRequest=null;renderReference();
  try{
    if(file.size>10*1024*1024)throw Error('10MB 이하의 이미지를 선택해 주세요.');
    const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('이미지 파일을 읽을 수 없습니다.'));reader.readAsDataURL(file);});
    uploadedReference=await post('/api/video/reference',{data:encoded});$('video-text-only').checked=false;saveDraft();notify(persona()?.portrait_url?'추가 장면 참고 이미지를 저장했습니다. 인물 기준 사진은 유지합니다.':'이 영상의 기준 이미지를 저장했습니다.');
  }catch(error){notify(error.message);}finally{uploading=false;renderReference();}
};
$('video-form').onsubmit=async e=>{e.preventDefault();if(generating||!state)return;const p=persona(),s=source();if(!p)return;generating=true;renderReference();renderEstimate();try{if(!pendingRequest)pendingRequest={request_key:crypto.randomUUID(),persona_id:p.id,persona_version:p.version,title:$('video-title').value,storyboard:$('video-storyboard').value,caption:$('video-caption').value,voice_script:$('video-voice-script').value,duration:Number($('video-duration').value),resolution:$('video-resolution').value,source_content_id:s?.id||null,source_version:s?.current_version||null,reference_media:uploadedReference?.media||null,text_only:$('video-text-only').checked,accept_estimated_cost:true,guide_versions:Object.fromEntries((videoState.guides||[]).filter(g=>g.enabled).map(g=>[g.id,g.version]))};const job=await post('/api/video/jobs',pendingRequest);notify('영상 요청을 저장했습니다. 제작 기록에서 진행 상태를 확인하세요.');await refresh();if(job.result?.content_id)openReview(job.result.content_id);}catch(error){notify(error.message);if(error.status&&error.status<500){pendingRequest=null;await refresh().catch(()=>{});}}finally{generating=false;renderReference();renderEstimate();}};
function renderGuides(){
  const active=(videoState.guides||[]).filter(g=>g.enabled);
  $('guide-applied').textContent=active.length?'MD 관여도 낮음 · 참고: '+active.map(g=>g.filename+' · v'+g.version).join(', '):'참고 MD 없음 · 콘텐츠 제작에서 공통 지침을 등록할 수 있습니다.';
}
function renderJobs(){const signature=JSON.stringify(videoState.jobs);if(signature===jobsSignature)return;jobsSignature=signature;const list=$('video-jobs');list.replaceChildren();if(!videoState.jobs.length)list.append(node('p','아직 영상 제작 기록이 없습니다.','video-empty'));for(const job of videoState.jobs){const article=node('article',undefined,'video-job');article.append(node('h3',job.input.title),node('span',labels[job.status]||job.status,'video-badge'),node('p',job.input.duration+'초 · '+job.input.resolution+' · 예상 $'+job.estimated_cost.toFixed(2)),node('p',new Date(job.created_at).toLocaleString('ko-KR')));if(job.input.guides?.length){const details=node('details',undefined,'video-job-guides');details.append(node('summary','적용한 MD '+job.input.guides.length+'개'));for(const guide of job.input.guides)details.append(node('p',guide.filename+' · v'+guide.version),node('pre',guide.content,'video-markdown'));article.append(details);}else article.append(node('p','적용한 MD 없음'));if(job.external_id)article.append(node('p','Segmind 작업 ID: '+job.external_id));if(job.error)article.append(node('p',job.error,'video-error'));if(job.next_retry_at)article.append(node('p','자동 복구 '+(job.sync_errors||job.poll_errors||0)+'회 · 다음 확인 '+new Date(job.next_retry_at).toLocaleTimeString('ko-KR')));if(job.sync_error)article.append(node('p',(job.status==='completed'?'영상은 저장되어 있습니다. ':'')+'제작 단계 반영 확인 필요: '+job.sync_error,'video-error'));if(job.result?.metrics?.cost!==undefined)article.append(node('p','Segmind 기록 비용: $'+job.result.metrics.cost));if(job.result?.content_id){const button=node('button','영상 검토','button');button.type='button';button.onclick=()=>openReview(job.result.content_id);article.append(button);}const syncOnly=['queued','running','downloading','completed'].includes(job.status)&&job.sync_pending&&job.sync_error;if(['uncertain','attention'].includes(job.status)||syncOnly){let input;if(!job.external_id&&!syncOnly){const label=node('label','Segmind에서 확인한 기존 작업 ID');input=node('input');input.autocomplete='off';label.append(input);article.append(label);}const resume=node('button',syncOnly?(job.status==='completed'?'저장된 결과 반영 재개':'단계 반영 재개'):'기존 작업 결과 조회 재개','button');resume.type='button';resume.onclick=async()=>{resume.disabled=true;try{await post('/api/video/jobs/'+job.id+'/resume',{external_id:input?.value});await refresh();notify('새 생성 요청 없이 저장된 작업 복구를 재개합니다.');}catch(error){notify(error.message);}finally{resume.disabled=false;}};article.append(resume);}list.append(article);}}
function openReview(id){if(reviewDirty&&!confirm('저장하지 않은 문안이 있습니다. 다른 영상을 볼까요?'))return;reviewId=id;reviewDirty=false;reviewSignature='';renderReview();$('video-review').scrollIntoView({behavior:'smooth',block:'start'});}
function renderReview(){const content=state?.contents.find(c=>c.id===reviewId);$('video-review').hidden=!content;if(!content)return;const frozen=['posting','published','uncertain'].includes(content.status);$('review-save').disabled=frozen;$('review-approve').disabled=frozen||reviewDirty||content.status==='approved';if(reviewDirty){if(reviewVersion!==content.current_version)$('review-note').textContent='다른 곳에서 새 버전이 저장되었습니다. 작성 중인 내용은 유지되며 저장 시 버전을 확인합니다.';return;}const signature=JSON.stringify([content.id,content.current_version,content.status]);if(signature===reviewSignature)return;reviewSignature=signature;reviewVersion=content.current_version;$('review-title').value=content.payload.title;$('review-caption').value=content.payload.caption;$('review-version').textContent='버전 '+reviewVersion+' · '+(content.status==='approved'?'승인됨 · 게시 대기':'검토 대기');const url='/media/'+content.payload.cards[0].media;if($('review-player').getAttribute('src')!==url)$('review-player').src=url;$('review-export').href='/api/contents/'+content.id+'/export';$('review-note').textContent='수정 후에는 다시 승인해야 합니다.';}
for(const id of ['review-title','review-caption'])$(id).addEventListener('input',()=>{reviewDirty=true;$('review-approve').disabled=true;});
$('review-form').onsubmit=async e=>{e.preventDefault();$('review-save').disabled=true;try{await post('/api/contents/'+reviewId+'/edit',{base_version:reviewVersion,title:$('review-title').value,caption:$('review-caption').value});reviewDirty=false;reviewSignature='';await refresh();notify('새 버전으로 저장했습니다.');}catch(error){notify(error.message);}finally{$('review-save').disabled=false;}};
$('review-approve').onclick=async()=>{if(reviewDirty)return;$('review-approve').disabled=true;try{await post('/api/contents/'+reviewId+'/approve',{version:reviewVersion});await refresh();notify('이 버전을 승인했습니다. Instagram 연결 전에는 게시 대기로 보관합니다.');}catch(error){notify(error.message);$('review-approve').disabled=false;}};
$('video-refresh').onclick=()=>refresh().catch(e=>notify(e.message));
window.addEventListener('beforeunload',e=>{if(reviewDirty){e.preventDefault();e.returnValue='';}});
renderEstimate();refresh().catch(e=>notify(e.message));setInterval(()=>refresh().catch(()=>{$('video-connection').textContent='로컬 서버 연결 확인 필요';}),5000);
